// <auto-generated />
namespace PhoneShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class memberV4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(memberV4));
        
        string IMigrationMetadata.Id
        {
            get { return "202004101321504_memberV4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
